# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='Temp_F',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='reading_time',
            field=models.DateTimeField(verbose_name='date output'),
        ),
    ]
