# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0007_auto_20170226_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='Temp_F',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='reading_time',
            field=models.IntegerField(verbose_name='date output'),
        ),
    ]
