# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0008_auto_20170226_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='reading_time',
            field=models.DateTimeField(verbose_name='date output'),
        ),
    ]
