# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0011_auto_20170228_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='reading_time',
            field=models.CharField(max_length=10, verbose_name='date output'),
        ),
    ]
