# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0014_auto_20170228_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Humidity',
        ),
    ]
