# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempsensor', '0016_auto_20170302_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='reading_time',
            field=models.DateTimeField(verbose_name='date output'),
        ),
    ]
